### ISSUE TITLE
`htmx:redirect:/path` and `new HtmxDirectView("/path")` have different behaviour regarding RedirectAttributes

### ISSUE THREAD

**Issue by wimdeblauwe** [wimdeblauwe/htmx-spring-boot#144]
I am writing a blog post on redirect attributes and I was testing this with the new 3.6.0 release. What I have discovered is that there is a difference when using `htmx:redirect:/path` versus `new HtmxDirectView("/path")`. The flash attributes are not present after the redirect in the first case, but they do work fine when using `new HtmxDirectView("/path")`.

**Comment by wimdeblauwe** [comment]
I tried to investigate how to fix it, but I don't quite understand the code at `HtmxResponseHandlerMethodArgumentResolver`. Should `supportsParameter` also check for `String.class`? But what should happen inside `resolveArgument` when it is a `String`?

**Comment by xhaggi** [comment]
There should be, or rather, there is no difference between string-based and view-based redirects.  BTW the `HtmxResponseHandlerMethodArgumentResolver` is not involved in view resolution such as `HtmxRedirectView`. Instead, this is done by Spring's view resolver implementation, since `HtmxRedirectView` is a subclass of `RedirectView`. So we don't do anything special to get it to work. The only difference between the two is that `HtmxRedirectView` is created by `[HtmxViewResolver](https://github.com/wimdeblauwe/htmx-spring-boot/blob/main/htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxViewResolver.java)` when you use string-based redirection.

To be really sure, I have created two new tests for this in #145.

**Comment by xhaggi** [comment]
Mhhh you're right @wimdeblauwe. The tests in #145 fail. Didn't check the result before I added my comment 😄 Let me check what's going on here.

**Comment by xhaggi** [comment]
Bad news. It won't work for string-based redirects because we need to set `mavContainer.setRedirectModelScenario(true)` on the `ModelAndViewContainer`, but in this case we do not have access to it, nor we are able to override anything. If a string-based return value is used, Spring's [ViewNameMethodReturnValueHandler](https://github.com/spring-projects/spring-framework/blob/main/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/ViewNameMethodReturnValueHandler.java) kicks in before a custom `HandlerMethodReturnValueHandler` is called, and you cannot change this order or override anything to change it (see [RequestMappingHandlerAdapter.java#L770](https://github.com/spring-projects/spring-framework/blob/main/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/RequestMappingHandlerAdapter.java#L770)

Of course, this is anything but nice. So what should we do? Point this out in the README or remove support for string-based redirects.

**Comment by xhaggi** [comment]
Another option would be to change the prefix from `htmx:redirect` and `htmx:location` to `redirect:htmx`, `redirect:htmx:location`. This will fix the issue. I have added another commit to the PR. Let me know if this could be an option.

**Comment by wimdeblauwe** [comment]
Thanks for investigating this. Changing the prefix seems the best option. I tried it in my example with the changes you did in the PR and it works fine. I'll do a 3.6.1 release with the fix.
